Wit's Analysis Competition
crypto-lake/analysis-sharing pull request #1
Opened 2022-12-09 15:16 UTC by witwender

*Description of your contribution goes here*
Using crypto-lake's sample data I've explored FTRB-USDT and BTC-USDT. It was a very good educational experience.

2022-12-10 14:47 UTC, Cyb3rN8 commented
You may consider the following:

1. Volume intrady-pattern due to open-hours of Asian, European and US Stock Exchange. It explains your "intraday  seasonality of spread".
2. Make sure you have performed timeseries segmentation and stationarity test before any AR modeling.

2022-12-13 15:12 UTC, leftys requested changes
Added a few comments. You don't have to address all of them, I will merge it once you're ready. Thanks for a nice analysis!

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "!pip install lakeapi"
outside collab, people would need statsmodels and matplotlib, that are not in requirements.txt.

how about adding all three here, lakeapi, statsmodels and matplotlib and if user has one of them already, they will just got skipped from the installation. also i suggest quiet mode: `pip install -q`

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "l1 = book[['received_time', 'bid_0_price', 'bid_0_size', 'ask_0_price', 'ask_0_size']]"
i uploaded level_1 data from 2022-10-01 to 2022-10-15 if you want. thats 5x more data than in book and you can load it directly from l1

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "Looks like BTC-USDT, no gaps."
there can actually be small gaps, but they won't be visible in the chart, because you didn't set x-axis to time.

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "df4 = df3.resample('5min').first()\n",
tip: you could use resample().mean() instead of first to get data with less noise. here you basically take "random" first row spread, which might be less descriptive than mean

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "df5.plot.scatter(x = 'ratio', y = 'log_returns', xlim = (0,6))"
nice idea to use this ratio (often called orderbook imbalance) as volatility indicator!

this  has one issue: the ratio is in range 0--infinity and is not symmetric. therefore buy imbalance situations have ratio of 10+ and are cut off from the chart. it would bebetter to use the standard imbalance definition `(bid_0_size - ask_0_size)/(bid_0_size + ask_0_size)`. it is in range [-1; 1] and is symmetric.

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "I've crashed Colab a few times trying to crunch the entire dataframe. I'll create a new dataframe that contains the data that we'll be looking at. Still the ratio but aggregating the L2 book
a few memory tips: don't use too many separate dataframes (df1--df10), drop unneeded data (deep book levels), use df.memory_usage().sum() for debugging.

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "I've crashed Colab a few times trying to crunch the entire dataframe. I'll create a new dataframe that contains the data that we'll be looking at. Still the ratio but aggregating the L2 book
you can even `del df123` at the end of cells to free some memory

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "l2['log_returns'] = np.log(l2['mid_price'] / l2['mid_price'].shift(1))\n",
it seems you don't do resample() here for the whole l2 data, which means this log_return will be only the return in a fraction of second between consequential order book updates. it would imho be much better to use eg. shift(100), which should be around 20 seconds on average. or resampling at the beginning, maybe just to a few seconds, would save you memory.

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "plt.plot(l2['ratio'], slope * l2['ratio'] + intercept, color = 'red')"
using the symmetric order book imbalance instead of ratio would help here a lot too!

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXQAAAEICAYAAABPgw/pAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliL
this is a nice result. actually it says that with 0 fees (big volume), you can get profitable from quoting 7 bps deep on average. and around 15 bps depth, you can get profitable (on smaller volume) even with quite big fees if you would manage your inventory super-well and had very small execution latency.

overall, i agree btc on the biggest exchange is just too competitive for small MM.

2022-12-13 15:12 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +            "image/png": "iVBORw0KGgoAAAANSUhEUgAAAXQAAAEICAYAAABPgw/pAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAALEgAACxIB0t1+/AAAADh0RVh0U29mdHdhcmUAbWF0cGxvdGxpYiB2ZXJzaW9uMy4yLjIsIGh0dHA6Ly9tYXRwbG90bGliL
:pray:

thanks for the nice analysis!

2022-12-14 14:25 UTC, witwender commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "plt.plot(l2['ratio'], slope * l2['ratio'] + intercept, color = 'red')"
Hmm, the redoing with orderbook imbalance helps the effect plot much weaker than the crazy level ratios suggest. This seems to be a good thing.

2022-12-14 15:26 UTC, witwender commented
Changes made

2022-12-15 17:00 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +        "df5.plot.scatter(x = 'ratio', y = 'log_returns', xlim = (0,6))"
You kept this in the notebook, but its no longer true:

> I had the cut off at 75th percentile of 6 bid/ask ratio...

2022-12-15 17:13 UTC, leftys requested changes
Even more interesting results here, nice. I have one more small comment and we can merge.

2022-12-15 17:13 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +              "
another cool result: even though slope might be close to zero, selling the biggest imbalances would be very profitable lately. also outside bear market, buying the lowest imbalances might work too.

2022-12-15 17:13 UTC, leftys commented on exploratory_analysis/Crypto_Microstructure_BTC_USDT_Exploratory_Analysis.ipynb
> +              "
the plot doesn't lie: there is really a strong short-timeframe anticorrelation. its just hard to use it for trading profitably.

2022-12-16 11:22 UTC, merged

2022-12-16 11:22 UTC, leftys commented
Thanks for the great analysis, merged!